### ISSUE TITLE
0.2.1 cannot be installed on AppVeyor

### ISSUE THREAD

**Issue by QuLogic** [jupyterlab/jupyterlab_pygments#18]
## Description

0.2.1 cannot be installed on AppVeyor, or possibly Windows in general. Our Azure CI is working on Windows, but is using a much older version of setuptools, so this may be the cause of the problem.

The last working build is [here](https://ci.appveyor.com/project/matplotlib/matplotlib/builds/43208758/job/2fcxhfgcd5h05vqy?fullLog=true), which installed 0.2.0. The first failing build is [here](https://ci.appveyor.com/project/matplotlib/matplotlib/builds/43230141/job/0kaejj9uu6uaplcw), where it starting trying 0.2.1.

## Reproduce

Sorry, we don't explicitly install this, and I don't know what pulls it in, so I don't have an easy install line. The result is:

```
ERROR: Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-install-qcjboywg\\jupyterlab-pygments\\jupyterlab_pygments-0.2.1.data/data/share/jupyter/labextensions/jupyterlab_pygments/static/vendors-node_modules_css-loader_dist_runtime_api_js-node_modules_css-loader_dist_runtime_cssW-72eba1.a3589cd972271a982c03.js'
```

## Context

- Operating System and version: Windows Server
- Browser and version: N/A
- JupyterLab version: N/A

**Comment by bollwyvl** [comment]
Yeah that path is too long for most stock windows machines... 0.2.1
probably just needs to be re-done entirely e.g. 0.2.2.

**Comment by martinRenou** [comment]
Thanks for reporting, will make a 0.2.2 release and make sure this file is not around

**Comment by martinRenou** [comment]
Should be fixed on the PyPi release, conda-forge release should come soonish :)

**Comment by QuLogic** [comment]
Thanks, our AppVeyor builds are working again already.
