### ISSUE TITLE
(Alpha) version compatible with JupyterLab 4?

### ISSUE THREAD

**Issue by bollwyvl** [jupyterlab/jupyterlab_pygments#26]
### Problem

When building `jupyterlab 4.0.0a31`:

https://github.com/conda-forge/jupyterlab-feedstock/pull/350#issuecomment-1321245641

```
+ jupyter labextension list
JupyterLab v4.0.0a31
/home/conda/feedstock_root/build_artifacts/jupyterlab_1668971729072/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/share/jupyter/labextensions
        jupyterlab_pygments v0.2.2 enabled  X (python, jupyterlab_pygments)


"jupyterlab_pygments@0.2.2" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension               Package
>=4.0.0-alpha.16 <4.1.0 >=3.1.0 <4.0.0          @jupyterlab/application
```

### Proposed Solution

Get an alpha out that lab4 can start building against.

### Additional context

- may be relevant to break up in #23

**Comment by RRosio** [comment]
I've been trying to update some extensions to the latest alpha version of JupyterLab 4 and in doing so ran into this message. I stated [updating the JupyterLab version on my fork](https://github.com/RRosio/jupyterlab_pygments/tree/lab4_alpha), but if there is a possibility that we can get an official release of an alpha version of jupyterlab_pygments that would be great!

**Comment by martinRenou** [comment]
Great! Would you like to open a PR from your branch @RRosio ?

**Comment by parmentelat** [comment]
I'd like to +1 an alpha release

the worrying message 
```
        jupyterlab_pygments v0.2.2 enabled  X (python, jupyterlab_pygments)
```
shows up immediately after a basic `pip install jupyterlab` 

my feeling is it might be a red herring (as I am seeing other issues here and there with jlab4&nb7), but I can't tell for sure

**Comment by frenzymadness** [comment]
In Fedora Linux we already have JupyterLab 4 so I'm not able to update jupyterlab_pygments as an RPM package. New release compatible with the latest jupyterlab would be great.

**Comment by krassowski** [comment]
A help with configuring releaser tokens for jupyterlab-pygments would be appreciated! Specifically I cannot upload the new version to either PyPI nor npm, c-f https://github.com/jupyterlab/jupyterlab_pygments/issues/39 and the issue with rights in the new `jupyter` org. Alternatively, someone who has the rights can make the release manually.

**Comment by martinRenou** [comment]
I'll make a manual release. Let's rename the NPM package after the release.

**Comment by krassowski** [comment]
Thank you @martinRenou!

Closing as 0.3.0 is now available on PyPI https://pypi.org/project/jupyterlab-pygments/0.3.0/, and confirmed to install well:

```
        jupyterlab_pygments v0.3.0 enabled OK (python, jupyterlab_pygments)
```
