### ISSUE TITLE
AssertionError: wrong color format 'var(--jp-mirror-editor-variable-color)'

### ISSUE THREAD

**Issue by shuai-zhou** [jupyterlab/jupyterlab_pygments#5]
We have an issue when using Sphinx for documentation. Looks like there is an issue in jupyterlab_pygments about color style. Could you please go to [here](https://github.com/sphinx-doc/sphinx/issues/8198) for some of the discussion and help us figure out what is going wrong? Thanks.

**Comment by eric-wieser** [comment]
This is not a `jupyter_lab-pygments` issue, it's a `readthedocs` or `pip` issue. What's happening is that readthedocs is specifically requesting an incompatible version of `pygments`, and then `pip` is not updating it. `pip` _is_ however detecting that the version is incompable, as the readthedocs build contains:

```
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

jupyterlab-pygments 0.1.1 requires pygments<3,>=2.4.1, but you'll have pygments 2.3.1 which is incompatible.
nbconvert 6.0.2 requires pygments>=2.4.1, but you'll have pygments 2.3.1 which is incompatible.
```
In my opinion, the simplest fix here is to ask readthedocs to stop installing the old version first.

**Comment by SylvainCorlay** [comment]
Thanks for responding @eric-wieser. Indeed this is not an issue with jupyterlab-pygments.

**Comment by domeckert** [comment]
I had the same issue, and indeed I can confirm it is fixed by forcing readthedocs to install a newer version of pygments. I have done this by adding

`pygments>=2.4.1`

to my requirements.txt file

**Comment by YichaoOU** [comment]
@domeckert Thanks! It worked!

**Comment by digizeph** [comment]
Thank you @domeckert !
I have to do a `pip3 install --upgrade Pygments` on my current system to make it work. I guess the default installed version is too low.
