### ISSUE TITLE
How to actually use this?

### ISSUE THREAD

**Issue by johnnybarrels** [jupyterlab/jupyterlab_pygments#9]
Found mention of this theme on the Jupyter blog here:

https://blog.jupyter.org/the-templating-system-of-nbconvert-6-47ea781eacd2

I love the idea, but can't find a single mention anywhere of how to actually use this? Is it supposed to be specified as a template to `nbconvert` like:

```sh
 jupyter nbconvert --to html --template jupyterlab_pygments
```

or something similar? This doesn't work for me after `pip` installing the `jupyterlab-pygments`.

**Comment by SylvainCorlay** [comment]
`jupyterlab-pygments` is a pygments theme. It is a dependency of nbconvert.

When exporting notebook to HTML with nbconvert, this pygment theme is used.
